# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sphinx-Config
version:      0.01
version_from: lib/Sphinx/Config.pm
installdirs:  site
requires:
    Carp:                          0
    FindBin:                       0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
